# ===========================================
# Unum Infrastructure - Outputs
# ===========================================

# ============ DynamoDB ============

output "dynamodb_table_name" {
  description = "Name of the DynamoDB table"
  value       = aws_dynamodb_table.main.name
}

output "dynamodb_table_arn" {
  description = "ARN of the DynamoDB table"
  value       = aws_dynamodb_table.main.arn
}

# ============ S3 ============

output "s3_bucket_name" {
  description = "Name of the S3 bucket"
  value       = aws_s3_bucket.media.id
}

output "s3_bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = aws_s3_bucket.media.arn
}

output "s3_bucket_region" {
  description = "Region of the S3 bucket"
  value       = aws_s3_bucket.media.region
}

# ============ IAM ============

output "iam_user_name" {
  description = "Name of the IAM user"
  value       = aws_iam_user.app.name
}

output "iam_user_arn" {
  description = "ARN of the IAM user"
  value       = aws_iam_user.app.arn
}

output "iam_access_key_id" {
  description = "Access key ID for the IAM user"
  value       = aws_iam_access_key.app.id
  sensitive   = false
}

output "iam_secret_access_key" {
  description = "Secret access key for the IAM user"
  value       = aws_iam_access_key.app.secret
  sensitive   = true
}

# ============ Environment File ============

output "env_file_content" {
  description = "Content for .env file"
  sensitive   = true
  value       = <<-EOT
    # AWS Configuration for Unum (${var.environment})
    # Generated by Terraform on ${timestamp()}

    AWS_REGION=${var.aws_region}
    AWS_ACCESS_KEY_ID=${aws_iam_access_key.app.id}
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.app.secret}

    # Resource Names
    DYNAMO_TABLE=${aws_dynamodb_table.main.name}
    S3_BUCKET=${aws_s3_bucket.media.id}

    # Feature Flags
    USE_AWS_BACKEND=true
    ENABLE_OFFLINE_SYNC=true
    ENABLE_BACKGROUND_SYNC=true
  EOT
}

# ============ Summary ============

output "setup_summary" {
  description = "Summary of created resources"
  value       = <<-EOT

    ================================================
    Unum Infrastructure Setup Complete!
    ================================================

    Environment: ${var.environment}
    Region: ${var.aws_region}

    Resources:
      DynamoDB Table: ${aws_dynamodb_table.main.name}
      S3 Bucket: ${aws_s3_bucket.media.id}
      IAM User: ${aws_iam_user.app.name}

    Next Steps:
      1. Run: terraform output -raw env_file_content > ../../.env
      2. Set USE_AWS_BACKEND=true in constants
      3. Upgrade to Node.js v20+
      4. Run: npx expo prebuild --clean
      5. Run: npx expo run:ios

  EOT
}
