# ===========================================
# Unum Infrastructure - Outputs
# ===========================================

# ============ DynamoDB ============

output "dynamodb_table_name" {
  description = "Name of the DynamoDB table"
  value       = aws_dynamodb_table.main.name
}

output "dynamodb_table_arn" {
  description = "ARN of the DynamoDB table"
  value       = aws_dynamodb_table.main.arn
}

# ============ S3 ============

output "s3_bucket_name" {
  description = "Name of the S3 bucket"
  value       = aws_s3_bucket.media.id
}

output "s3_bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = aws_s3_bucket.media.arn
}

output "s3_bucket_region" {
  description = "Region of the S3 bucket"
  value       = aws_s3_bucket.media.region
}

# ============ Cognito ============

output "cognito_identity_pool_id" {
  description = "Cognito Identity Pool ID (safe to commit - not a secret)"
  value       = aws_cognito_identity_pool.main.id
}

output "cognito_identity_pool_name" {
  description = "Cognito Identity Pool name"
  value       = aws_cognito_identity_pool.main.identity_pool_name
}

output "cognito_authenticated_role_arn" {
  description = "ARN of the IAM role for authenticated users"
  value       = aws_iam_role.cognito_authenticated.arn
}

output "cognito_unauthenticated_role_arn" {
  description = "ARN of the IAM role for unauthenticated (guest) users"
  value       = aws_iam_role.cognito_unauthenticated.arn
}

# ============ Environment File (Cognito-based - NO SECRETS) ============

output "env_file_content" {
  description = "Content for .env file (safe to commit - no secrets)"
  sensitive   = false
  value       = <<-EOT
    # AWS Configuration for Unum (${var.environment})
    # Generated by Terraform
    # NOTE: This file contains NO secrets and is safe to commit to git

    # Environment
    APP_ENV=${var.environment == "prod" ? "production" : "development"}

    # AWS Region
    AWS_REGION=${var.aws_region}

    # Cognito Identity Pool (NOT a secret - just an identifier)
    COGNITO_IDENTITY_POOL_ID=${aws_cognito_identity_pool.main.id}

    # Resource Names
    DYNAMO_TABLE=${aws_dynamodb_table.main.name}
    S3_BUCKET=${aws_s3_bucket.media.id}

    # Auth Backend API
    AUTH_API_URL=${aws_apigatewayv2_api.auth.api_endpoint}

    # Feature Flags
    USE_AWS_BACKEND=true
    ENABLE_OFFLINE_SYNC=true
    ENABLE_BACKGROUND_SYNC=${var.environment == "prod" ? "true" : "false"}
    USE_TEST_DATA=${var.environment == "prod" ? "false" : "true"}
    DEBUG=${var.environment == "prod" ? "false" : "true"}
  EOT
}

# ============ Legacy IAM User (DEPRECATED - will be removed) ============
# These outputs are kept temporarily for migration purposes.
# Remove after migrating to Cognito.

output "iam_user_name" {
  description = "DEPRECATED: Name of the IAM user"
  value       = aws_iam_user.app.name
}

output "iam_access_key_id" {
  description = "DEPRECATED: Access key ID for the IAM user"
  value       = aws_iam_access_key.app.id
  sensitive   = false
}

output "iam_secret_access_key" {
  description = "DEPRECATED: Secret access key for the IAM user"
  value       = aws_iam_access_key.app.secret
  sensitive   = true
}

# ============ Summary ============

output "setup_summary" {
  description = "Summary of created resources"
  value       = <<-EOT

    ================================================
    Unum Infrastructure Setup Complete!
    ================================================

    Environment: ${var.environment}
    Region: ${var.aws_region}

    Resources:
      DynamoDB Table: ${aws_dynamodb_table.main.name}
      S3 Bucket: ${aws_s3_bucket.media.id}
      Cognito Identity Pool: ${aws_cognito_identity_pool.main.id}

    Next Steps:
      1. Copy env file: terraform output -raw env_file_content > ../../.env.${var.environment == "prod" ? "production" : "development"}
      2. Install Cognito SDK: npm install @aws-sdk/client-cognito-identity
      3. Run: npx expo start
      4. Test sign-in with Apple

    NOTE: The env file contains NO secrets and is safe to commit to git.

  EOT
}
